-- Patient data
insert into Patient (patientID, firstName, lastName, birthDate, age) values (1, 'Orson', 'Brownsey', '2002-09-10', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (2, 'Alvin', 'Behnecken', '2000-01-23', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (3, 'Belia', 'Hawney', '2005-10-18', 17);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (4, 'Stace', 'Chillistone', '2002-05-03', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (5, 'Trueman', 'Huxster', '1999-03-04', 23);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (6, 'Normand', 'Novello', '1999-12-30', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (7, 'Law', 'Bladon', '2002-08-07', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (8, 'Callie', 'Tassel', '2000-07-15', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (9, 'Trumaine', 'Barnewille', '2000-09-08', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (10, 'Marji', 'Lyddiard', '2001-10-21', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (11, 'Corly', 'Creeber', '2004-06-05', 18);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (12, 'Krisha', 'Denge', '2003-12-13', 18);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (13, 'Karel', 'Juzek', '2002-05-29', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (14, 'Leyla', 'Munson', '1999-06-14', 23);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (15, 'Stanton', 'Valerio', '2002-06-17', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (16, 'Ilise', 'Collman', '2001-03-18', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (17, 'Carey', 'Roistone', '2000-09-17', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (18, 'Rosalinda', 'Chapleo', '2001-07-03', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (19, 'Raven', 'Kivelle', '2001-01-06', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (20, 'Ardine', 'Headford', '2002-03-04', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (21, 'Ashli', 'Ludlem', '2000-06-11', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (22, 'Fonz', 'Littledike', '2000-07-30', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (23, 'Jasmin', 'Merrydew', '1999-01-28', 23);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (24, 'Giulietta', 'Brick', '2000-04-07', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (25, 'Jameson', 'Moules', '2001-11-06', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (26, 'Karola', 'de''-Ancy Willis', '2004-04-03', 18);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (27, 'Orson', 'Utteridge', '2004-07-03', 18);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (28, 'Eula', 'Hutchcraft', '2005-09-13', 17);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (29, 'Doro', 'Wyman', '2000-10-05', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (30, 'Haywood', 'Cauldfield', '2002-12-26', 19);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (31, 'Rosalinde', 'Delmage', '2001-04-14', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (32, 'Jammal', 'Lomasney', '2000-02-18', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (33, 'Avrit', 'Redier', '2000-04-26', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (34, 'Steffie', 'McDirmid', '2001-08-11', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (35, 'Yevette', 'Faull', '2005-02-14', 17);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (36, 'Justinn', 'Wagon', '2004-07-09', 18);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (37, 'Fairfax', 'Carillo', '2003-02-15', 19);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (38, 'Galen', 'Whyley', '2002-05-19', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (39, 'Lew', 'Leadbitter', '2000-12-08', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (40, 'Marshall', 'Easbie', '2000-09-28', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (41, 'Marya', 'Perree', '2003-04-12', 19);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (42, 'Nada', 'Matveichev', '2000-04-26', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (43, 'Felizio', 'Kenny', '2002-05-05', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (44, 'Rolph', 'Hutcheon', '1999-07-26', 23);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (45, 'Fowler', 'Alenichev', '2005-08-03', 17);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (46, 'Carilyn', 'Gerhold', '2003-09-16', 19);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (47, 'Shannon', 'Anney', '2000-06-17', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (48, 'Cele', 'Waddilow', '2001-04-13', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (49, 'Mickey', 'Graham', '2001-02-07', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (50, 'Gertrude', 'Rijkeseis', '2002-06-14', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (51, 'Dav', 'Carnock', '2000-01-18', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (52, 'Giustino', 'O''Scollain', '2002-03-02', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (53, 'Ly', 'Dominguez', '2003-06-25', 19);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (54, 'Adi', 'Hauck', '2002-11-15', 20);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (55, 'Alejoa', 'Martineau', '2000-04-17', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (56, 'Marillin', 'Trowell', '2005-10-07', 17);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (57, 'Kimble', 'Harmeston', '2005-04-02', 17);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (58, 'Gayelord', 'Gwyllt', '2000-08-30', 22);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (59, 'Melinde', 'Soppett', '2001-02-18', 21);
insert into Patient (patientID, firstName, lastName, birthDate, age) values (60, 'Leigh', 'Asch', '2002-12-13', 19);


-- Doctor
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (1, 'Orthopedic Surgery', 'Bogart', 'Tattershaw', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (2, 'Orthopedic Surgery', 'Karoly', 'Shovelbottom', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (3, 'Ophthalmology', 'Juliane', 'McClymond', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (4, 'Ophthalmology', 'Patrice', 'Ruddick', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (5, 'Emergency Medicine', 'Lillian', 'Rawles', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (6, 'Oncology', 'Ulick', 'Lapre', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (7, 'Obstetrics and Gynecology', 'Welbie', 'Bengochea', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (8, 'Radiology', 'Carlos', 'Skep', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (9, 'Infectious Disease', 'Annabella', 'Stelfox', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (10, 'Allergy and Immunology', 'Casar', 'Seathwright', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (11, 'Pediatrics', 'Allan', 'Klaaassen', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (12, 'Family Medicine', 'Rayna', 'Colthard', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (13, 'Family Medicine', 'Addia', 'Bettanay', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (14, 'Gastroenterology', 'Belinda', 'Upwood', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (15, 'Geriatrics', 'Hyacinthia', 'Clunan', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (16, 'Emergency Medicine', 'Abran', 'Streeter', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (17, 'Internal Medicine', 'Cathyleen', 'Keppe', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (18, 'Otolaryngology (ENT)', 'Wit', 'Jeanes', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (19, 'Otolaryngology (ENT)', 'Julee', 'Edeson', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (20, 'Otolaryngology (ENT)', 'Natala', 'Diglin', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (21, 'Cardiology', 'Griffin', 'Heathwood', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (22, 'Orthopedic Surgery', 'Jonas', 'Rowlson', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (23, 'Obstetrics and Gynecology', 'Nelie', 'Heape', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (24, 'Endocrinology', 'Virgina', 'Massingberd', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (25, 'Psychiatry', 'Dalia', 'Scourge', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (26, 'Urology.', 'Emili', 'McAllester', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (27, 'Psychiatry', 'Fleming', 'Sandle', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (28, 'Gastroenterology', 'Hoyt', 'Dougary', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (29, 'Internal Medicine', 'Robinet', 'Rijkeseis', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (30, 'Sports Medicine', 'Herold', 'Lundie', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (31, 'Dermatology', 'Virgie', 'Flindall', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (32, 'Infectious Disease', 'Aldus', 'Baert', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (33, 'Gastroenterology', 'Yulma', 'Mewett', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (34, 'Family Medicine', 'Mortie', 'Gullick', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (35, 'Plastic Surgery', 'Dacia', 'Tatlowe', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (36, 'Endocrinology', 'Sydney', 'Cauldwell', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (37, 'Pathology', 'Viva', 'Tregona', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (38, 'Psychiatry', 'Larine', 'McBrearty', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (39, 'Physical Medicine and Rehabilitation', 'Helene', 'Lamba', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (40, 'Hematology', 'Brook', 'Birtwisle', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (41, 'Plastic Surgery', 'Alis', 'Melbourne', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (42, 'Hematology', 'Axel', 'Johanning', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (43, 'Cardiology', 'Rosana', 'Bertomieu', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (44, 'Pulmonology', 'Thomasa', 'Kislingbury', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (45, 'Gastroenterology', 'Neely', 'Chatenier', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (46, 'Allergy and Immunology', 'Anselm', 'Schleicher', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (47, 'Family Medicine', 'Vitia', 'Burleton', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (48, 'Plastic Surgery', 'Aundrea', 'Almak', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (49, 'Infectious Disease', 'Dur', 'Cheal', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (50, 'Nephrology', 'Cybil', 'Fawley', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (51, 'Internal Medicine', 'Viole', 'Gronaller', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (52, 'Sports Medicine', 'Todd', 'Dilliston', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (53, 'Nephrology', 'Morgan', 'Danielovitch', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (54, 'Rheumatology', 'Lock', 'Clink', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (55, 'Emergency Medicine', 'Vallie', 'Caddan', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (56, 'Neurology', 'Joye', 'Walenta', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (57, 'Dermatology', 'Kristine', 'Hardwell', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (58, 'Gastroenterology', 'Sigismund', 'Snoday', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (59, 'Radiology', 'Madelena', 'Dilks', 1);
insert into Doctor (doctorID, specialization, firstName, lastName, consent) values (60, 'Geriatrics', 'Delilah', 'Hollidge', 1);
